export const homeContent = {
  en: {
    introduction: "Indian flavours. Amsterdam evenings.",
    welcome: "A place to take your time.",
    welcomeText: "Fresh naan, aromatic curries and the warmth of the tandoor. Come for dinner, stay for the conversation. Welcome to Shah Restaurant in Amsterdam-Noord.",
    menu: "Menu", atmosphere: "Atmosphere", story: "Our story", visit: "Visit us",
    explore: "Discover Shah", reserve: "Reserve a table", order: "Order online",
    kitchen: "The kitchen", menuTitle: "Favourites, made with care.",
    menuText: "A selection from our kitchen. Discover the ingredients and find your next favourite.",
    signature: "Signature dishes", category: "Choose a menu category", fullMenu: "View the full menu",
    menuEmpty: "Our menu is being updated. Please call us for today's selection.",
    menuLoading: "Loading the menu", details: "View dish details", fromMenu: "From our menu",
    allergy: "Any allergies or dietary requirements? Please speak to our team before ordering.",
    galleryTitle: "The setting for your evening.", galleryText: "A glimpse of the food, the bar and the space we call home.",
    fullGallery: "View the gallery", enlarge: "Enlarge photo", close: "Close", previous: "Previous photo", next: "Next photo",
    table: "At the table", tandoor: "From the kitchen", bar: "At the bar",
    tableAlt: "Naan, dipping sauces and golden cutlery on a set table",
    dishAlt: "Indian curries, rice and naan served at a table at Shah Restaurant",
    barAlt: "The illuminated bar and dining space at Shah Restaurant",
    interiorAlt: "The dining room at Shah Restaurant in Amsterdam-Noord",
    storyLink: "Meet Shah Restaurant", storyAside: "Indian roots. A home in Amsterdam.",
    occasions: "Together at Shah", occasionsTitle: "Make an evening of it.",
    occasionsText: "A birthday, a family celebration or dinner with colleagues. Find the right setting for your occasion.",
    birthdays: "Birthdays", celebrations: "Celebrations", company: "Company catering",
    guestTitle: "In our guests' words.", guestCount: "guest reviews", outOf: "out of 5",
    visitTitle: "See you in Amsterdam-Noord.", directions: "Get directions", contact: "Contact", hours: "Opening hours",
    visitText: "Join us at Klaprozenweg 36a. Reserve online or call us to discuss your evening.",
    faq: "Before your visit", faqTitle: "A few useful details.",
    questions: [
      { question: "How do I book a table?", answer: "Reserve a table online or call +31 20 341 2995. For a larger party or a special occasion, contact our team to discuss the details." },
      { question: "Where can I find the menu?", answer: "Our full menu and current prices are available on the order page. You can also explore a selection of dishes above." },
      { question: "Can you help with dietary requirements?", answer: "Please let our team know about allergies or dietary requirements before ordering. We can discuss ingredients and suitable options with you." },
      { question: "Can I organise a celebration?", answer: "Contact us about birthdays, celebrations and company catering. Our events pages have more information for your occasion." },
    ],
    closing: "An evening worth making time for.", closingText: "Good food. Good company. Your table at Shah.",
    call: "Call us", email: "Email us", photo: "Photo", ingredients: "Ingredients", allergens: "Allergens",
    menuCount: "dishes", location: "Amsterdam-Noord", family: "Family hospitality", food: "Indian cuisine",
    pauseMotion: "Pause animations", resumeMotion: "Enable animations", reducedMotion: "Reduced motion is enabled on your device",
    searchMenu: "Search the menu", searchPlaceholder: "Find a dish or ingredient", clearSearch: "Clear search",
    noMatches: "No dishes match your search.", resetMenu: "Reset filters", showMore: "Show all matching dishes", showLess: "Show fewer dishes",
    popular: "Guest favourite", newDish: "New", allCategories: "All categories", menuSelection: "Your selection",
    evening: "Your evening, your way.", dine: "A table for you", dineText: "Settle in. We will take care of dinner.",
    takeaway: "Shah, at home", takeawayText: "Your favourites, wherever the evening takes you.",
    gather: "Better together", gatherText: "Bring your people. Make it an occasion.",
    exploreEvents: "Explore occasions", tableNote: "Dinner in Amsterdam-Noord", kitchenNote: "Fresh naan. Fragrant spices. A warm welcome.",
    viewPhoto: "View photo", photoNavigation: "Choose a photo",
    browseDishes: "Explore the dishes", drinksAlt: "A layered green and purple cocktail with foam at Shah Restaurant",
    drinks: "Something to sip", room: "A place to linger",
  },
  nl: {
    introduction: "Indiase smaken. Amsterdamse avonden.",
    welcome: "Een plek om de tijd te nemen.",
    welcomeText: "Verse naan, geurige curry's en de warmte van de tandoor. Kom voor het diner, blijf voor het gesprek. Welkom bij Shah Restaurant in Amsterdam-Noord.",
    menu: "Menukaart", atmosphere: "Sfeer", story: "Ons verhaal", visit: "Bezoek ons",
    explore: "Ontdek Shah", reserve: "Reserveer een tafel", order: "Online bestellen",
    kitchen: "De keuken", menuTitle: "Favorieten, met aandacht bereid.",
    menuText: "Een selectie uit onze keuken. Ontdek de ingrediënten en vind uw volgende favoriet.",
    signature: "Onze signatuurgerechten", category: "Kies een menucategorie", fullMenu: "Bekijk de hele menukaart",
    menuEmpty: "Onze menukaart wordt bijgewerkt. Bel ons voor de selectie van vandaag.",
    menuLoading: "Menukaart laden", details: "Bekijk het gerecht", fromMenu: "Van onze menukaart",
    allergy: "Allergieën of dieetwensen? Overleg vóór het bestellen met ons team.",
    galleryTitle: "Het decor van uw avond.", galleryText: "Een kijkje in onze keuken, aan de bar en in het restaurant.",
    fullGallery: "Bekijk de galerij", enlarge: "Vergroot de foto", close: "Sluiten", previous: "Vorige foto", next: "Volgende foto",
    table: "Aan tafel", tandoor: "Uit de keuken", bar: "Aan de bar",
    tableAlt: "Naan, dipsauzen en gouden bestek op een gedekte tafel",
    dishAlt: "Indiase curry's, rijst en naan op tafel bij Shah Restaurant",
    barAlt: "De verlichte bar en eetzaal van Shah Restaurant",
    interiorAlt: "De eetzaal van Shah Restaurant in Amsterdam-Noord",
    storyLink: "Maak kennis met Shah Restaurant", storyAside: "Indiase roots. Een thuis in Amsterdam.",
    occasions: "Samen bij Shah", occasionsTitle: "Maak er een mooie avond van.",
    occasionsText: "Een verjaardag, een familiefeest of een diner met collega's. Vind de juiste setting voor uw gelegenheid.",
    birthdays: "Verjaardagen", celebrations: "Feesten", company: "Bedrijfscatering",
    guestTitle: "In de woorden van onze gasten.", guestCount: "gastbeoordelingen", outOf: "van 5",
    visitTitle: "Tot ziens in Amsterdam-Noord.", directions: "Plan uw route", contact: "Contact", hours: "Openingstijden",
    visitText: "U vindt ons aan de Klaprozenweg 36a. Reserveer online of bel ons om uw avond te bespreken.",
    faq: "Voor uw bezoek", faqTitle: "Een paar praktische details.",
    questions: [
      { question: "Hoe reserveer ik een tafel?", answer: "Reserveer online of bel +31 20 341 2995. Neem voor een groter gezelschap of een speciale gelegenheid contact op met ons team." },
      { question: "Waar vind ik de menukaart?", answer: "Onze volledige menukaart en actuele prijzen staan op de bestelpagina. Hierboven vindt u alvast een selectie van onze gerechten." },
      { question: "Kunnen jullie rekening houden met dieetwensen?", answer: "Geef allergieën of dieetwensen vóór het bestellen door aan ons team. We bespreken graag de ingrediënten en mogelijke opties met u." },
      { question: "Kan ik een feest organiseren?", answer: "Neem contact met ons op voor verjaardagen, feesten en bedrijfscatering. Op onze evenementenpagina's vindt u meer informatie voor uw gelegenheid." },
    ],
    closing: "Een avond om tijd voor te maken.", closingText: "Goed eten. Goed gezelschap. Uw tafel bij Shah.",
    call: "Bel ons", email: "Mail ons", photo: "Foto", ingredients: "Ingrediënten", allergens: "Allergenen",
    menuCount: "gerechten", location: "Amsterdam-Noord", family: "Familiale gastvrijheid", food: "Indiase keuken",
    pauseMotion: "Animaties pauzeren", resumeMotion: "Animaties inschakelen", reducedMotion: "Uw apparaat staat ingesteld op minder beweging",
    searchMenu: "Zoek in de menukaart", searchPlaceholder: "Zoek een gerecht of ingrediënt", clearSearch: "Zoekopdracht wissen",
    noMatches: "Geen gerechten gevonden.", resetMenu: "Filters wissen", showMore: "Toon alle gevonden gerechten", showLess: "Toon minder gerechten",
    popular: "Favoriet bij onze gasten", newDish: "Nieuw", allCategories: "Alle categorieën", menuSelection: "Uw selectie",
    evening: "Uw avond, op uw manier.", dine: "Een tafel voor u", dineText: "Neem plaats. Wij zorgen voor het diner.",
    takeaway: "Shah, bij u thuis", takeawayText: "Uw favorieten, waar de avond u ook brengt.",
    gather: "Samen is het mooier", gatherText: "Breng uw gezelschap mee. Maak er iets bijzonders van.",
    exploreEvents: "Bekijk de gelegenheden", tableNote: "Dineren in Amsterdam-Noord", kitchenNote: "Verse naan. Geurige kruiden. Een warm welkom.",
    viewPhoto: "Bekijk foto", photoNavigation: "Kies een foto",
    browseDishes: "Ontdek de gerechten", drinksAlt: "Een gelaagde groene en paarse cocktail met schuim bij Shah Restaurant",
    drinks: "Iets om van te nippen", room: "Een plek om te blijven",
  },
};